### ISSUE TITLE
1.6.38 on iOS : Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by davesworking** [glennrp/libpng#452]
hi,

we're seeing this on iOS for 1.6.38:

```
                Undefined symbols for architecture arm64:
                  "_png_do_expand_palette_rgb8_neon", referenced from:
                      _png_do_read_transformations in libpng.a(pngrtran.c.o)
                  "_png_do_expand_palette_rgba8_neon", referenced from:
                      _png_do_read_transformations in libpng.a(pngrtran.c.o)
                  "_png_init_filter_functions_neon", referenced from:
                      _png_read_filter_row in libpng.a(pngrutil.c.o)
                  "_png_riffle_palette_neon", referenced from:
                      _png_do_read_transformations in libpng.a(pngrtran.c.o)
                ld: symbol(s) not found for architecture arm64
```

Thanks,
Dave

**Comment by davesworking** [comment]
hi, just checking on this to see if there is a fix.

**Comment by ctruta** [comment]
Hi, @davesworking,
Unfortunately, I don't have a fix, and worse yet, I don't have access to a Mac machine at this moment.

I did test the Mac build on ARM64 when I released v1.6.38, but I might have missed iOS. Setting up a test bot for iOS and Android builds is still on my to-do list.

Could you please investigate a bit further? For example: would you be able to tell if this is a regression from v1.6.37 or earlier, or if the error still occurs with v1.6.39? And, if at all possible, could you please contribute a fix?

**Comment by thenextman** [comment]
@ctruta As far as I can tell, I have the same issue on macOS arm64 on versions 1.6.36, .37 and .38. I'm investigating this on my side, but are you sure things are sound for macOS arm64?

**Comment by thenextman** [comment]
This does seem resolved for 1.6.39 as far as I can tell

**Comment by ctruta** [comment]
I confirm that I did, indeed, fix a bunch of ARM64-related issues between 1.6.38 and 1.6.39. It could be that this issue went away due to those other fixes.
Now I realize that, if you were building with CMake, you could have used the workaround
`-DCMAKE_C_FLAGS="-DPNG_ARM_NEON_OPT=0"`
but I'm glad to know that the problem is gone. Thank you for testing.
